const countries = [
  {
    name: "Germany",
    population: "81,770,900",
    region: "Europe",
    capital: "Berlin",
    img: "Germany.png",
  },
  {
    name: "United States of America",
    population: "323,947,000",
    region: "Americas",
    capital: "Washington, D.C.",
    img: "USA.png",
  },
  {
    name: "Brasil",
    population: "206,135,893",
    region: "Americas",
    capital: "Brasilia",
    img: "Brasil.png",
  },
  {
    name: "Iceland",
    population: "334,300",
    region: "Europe",
    capital: "Reykjavík",
    img: "Iceland.png",
  },
  {
    name: "Afghanistan",
    population: "27,657,145",
    region: "Asia",
    capital: "Kabul",
    img: "Afghanistan.png",
  },
  {
    name: "Aland Islands",
    population: "28,875",
    region: "Europe",
    capital: "Mariehamn",
    img: "AlanIslands.png",
  },
  {
    name: "Albania",
    population: "2,886,026",
    region: "Europe",
    capital: "Tirania",
    img: "Albania.png",
  },
  {
    name: "Algeria",
    population: "40,400,000",
    region: "Africa",
    capital: "Algiers",
    img: "Algeria.png",
  },
];
